VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ISort"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

' öffentliche Methoden

Public Function CBSortArchiveItems(ByVal Data1 As Long, ByVal Data2 As Long, Optional ByVal ZeroIfSameType As Boolean = False) As Long
  '
End Function

Public Function CBSortCommonItems(ByVal Data1 As Long, ByVal Data2 As Long) As Long
  '
End Function

Public Function CBSortGroups(ByVal Data1 As Long, ByVal Data2 As Long) As Long
  '
End Function
